### ISSUE TITLE
Generating float constants, doesn't add 'f'.

### ISSUE THREAD

**Issue by Justas-S** [Shoebill/wrapper-generator#3]
Here's a line from Constants.java generated from streamer.iml:

``` java
public static final float STREAMER_OBJECT_SD = 300.0;
```

Because there is no `f` at the end, it is considered a double and thus a type error is born.

Small issue, but worh noting :)

**Comment by 123marvin123** [comment]
Fixed with commit cb1ca292a8c4e4144c73ed4eb9d2acee6fbb7ee5 and d495fdffc3f01278943aa58f4b4715d6bb4dd91d. Thank you for the report.
